import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://covant.ai';
  const now = new Date();

  return [
    { url: base, lastModified: now, changeFrequency: 'weekly', priority: 1 },
    { url: `${base}/pricing`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/beta`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/features`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/product`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portal-preview`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/dashboard-preview`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/demo`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/integrations`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/integrations/salesforce`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/integrations/hubspot`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/integrations/webhooks`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/integrations/api`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/integrations/slack`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/integrations/stripe`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/compare`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/compare/partnerstack`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/compare/impact-com`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/compare/crossbeam`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/roi`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/about`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/changelog`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${base}/use-cases`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/use-cases/vp-partnerships`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/use-cases/revops`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/use-cases/partner-manager`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/assessment`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/faq`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/contact`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/apply`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/customers`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/resources`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/roadmap`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${base}/blog`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/blog/partner-program-kpis-metrics-to-track`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/partner-intelligence-data-driven-programs`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/partner-portal-partners-actually-use`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/measure-partner-program-roi`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/how-to-build-partner-commission-structure`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/partner-deal-registration-best-practices`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/why-partner-attribution-is-broken`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/true-cost-of-spreadsheet-partner-programs`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/blog/3-attribution-models-every-vp-should-know`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/status`, lastModified: now, changeFrequency: 'daily', priority: 0.5 },
    { url: `${base}/help`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${base}/glossary`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/templates`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/benchmarks`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/feed.xml`, lastModified: now, changeFrequency: 'weekly', priority: 0.3 },
    { url: `${base}/docs`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/privacy`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/terms`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/security`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/dpa`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
  ];
}
