"use client";

import Link from "next/link";
import {
  Zap, Wrench, Sparkles, GitCommit, ArrowLeft,
} from "lucide-react";

type Entry = {
  date: string;
  commits: { hash: string; type: "feat" | "fix" | "polish" | "other"; message: string }[];
};

// Generated from real git log — update periodically
const CHANGELOG: Entry[] = [
  {
    date: "March 9, 2026",
    commits: [
      { hash: "NEW0066", type: "feat", message: "Blog — new SEO article: \"Channel Sales Strategy: How to Build an Indirect Revenue Engine That Outperforms Direct\" — comprehensive guide targeting 'channel sales strategy,' 'indirect sales strategy,' and 'channel partner strategy.' Covers why most channel strategies fail (channel conflict, no attribution, undifferentiated economics, no enablement, set-and-forget mentality), the five components of a channel sales strategy (model selection, partner economics, deal flow operations, partner experience, measurement and attribution), designing your channel model (reseller vs referral vs co-sell with attribution model mapping), building the operational foundation (deal reg, commission engine, portal, attribution, conflict resolution), the 90-day channel launch playbook (infrastructure → first 5 partners → first deals → prove ROI → scale), 8 channel sales metrics that matter (sourced revenue, deal velocity, activation rate, commission-to-revenue ratio, registration volume, win rate by partner, deal size comparison, concentration risk), scaling from 10 to 100 partners (automated commissions, partner segmentation, self-serve, partner-led pipeline, standardized QBRs), channel vs direct sales complementarity (segment by deal size, geography, vertical, rules of engagement), how Covant powers channel sales strategy (three attribution models, commission engine, white-label portal, partner intelligence, conflict detection), and the channel readiness checklist. 24th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0065", type: "feat", message: "Blog — new SEO article: \"Ecosystem-Led Growth: How to Build a Partner Ecosystem That Drives Compounding Revenue\" — comprehensive guide targeting 'ecosystem-led growth,' 'ELG strategy,' and 'partner ecosystem strategy.' Covers what ELG actually means vs rebranded channel sales (multi-directional value, data as connective tissue, compounding returns, lifecycle coverage), the three layers of an ecosystem growth engine (account intelligence data foundation, co-sell orchestration motion layer, ecosystem flywheel compounding layer), attribution for ecosystem-led growth (multi-partner credit via Role Split, influence measurement through touchpoint tracking, lifecycle attribution beyond acquisition), building an ecosystem-led GTM motion (90-day sequence: map and prioritize → activate co-sell → build flywheel infrastructure → scale and compound), measuring ELG (ecosystem-influenced pipeline, co-sell win rate vs solo, ecosystem depth per customer, partner-to-partner pipeline, time to activation, ecosystem ROI), common ELG mistakes that kill momentum (rebranding referrals, tech partnerships without GTM, no shared data layer, treating all partners equally, measuring only acquisition, manual everything at scale), and how Covant powers ELG (account mapping engine, Role Split attribution, influence tracking, partner portal with ecosystem intelligence, lifecycle attribution). 23rd blog article. Added to sitemap and RSS feed. Ship Log stats updated to 23 blog articles, 135+ shipped items." },
      { hash: "NEW0064", type: "feat", message: "Blog — new SEO article: \"How to Build a Technology Partner Program That Drives Revenue\" — comprehensive guide targeting 'technology partner program,' 'ISV partner program,' and 'tech alliance partner program.' Covers why tech partnerships fail to generate revenue (no attribution model for influence, treating tech partners like resellers, integrations without go-to-market, no shared account visibility, wrong metrics), the three types of technology partnerships (integration partners/ISVs, technology alliances/platform partnerships, ecosystem/build-on partners), attribution models for tech partnerships (Role Split for co-sell, influence tracking for integrations, Source Wins for marketplace referrals, hybrid approach), building the account mapping engine (customer overlap, prospect overlap, whitespace identification, quarterly refresh, scoring and prioritization), incentive structures for tech partnerships (referral fees, influence bonuses, MDF for joint GTM, integration development support, tiered partnership benefits), the 90-day tech partner program launch playbook, measuring technology partnership ROI (influenced pipeline, co-sell win rate, deal size uplift, integration adoption rate, time to activation, revenue concentration, retention differential), common mistakes (integration without GTM, reseller metrics on tech partnerships, equal investment, no exec sponsors, premature announcements, ignoring partner incentives), and how Covant's Role Split attribution model and influence tracking power tech partner programs. Cross-links to Covant's Role Split model, account mapping, and partner analytics. 22nd blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0063", type: "feat", message: "Blog — new SEO article: \"How to Build a Reseller Program That Actually Scales\" — comprehensive guide targeting 'reseller program,' 'how to build a reseller program,' and 'channel reseller strategy.' Covers why most reseller programs stall at 20 partners (no deal registration, spreadsheet attribution, flat commissions, manual operations, no self-service), the five pillars of a scalable reseller program (deal registration with protection, auditable attribution, tiered commissions, partner portal with real-time visibility, automated commission calculation), setting up deal registration that partners actually use (short forms, auto-conflict detection, clear protection windows, automated approval with SLAs, confirmation with commission estimates), designing commission tiers that drive growth (3-4 tiers, revenue as primary qualifier, tangible tier benefits, rolling 12-month evaluation, product-specific rate adjustments), building the partner portal experience (dashboard with key numbers, in-portal deal reg, commission transparency, white-label, performance analytics), the 90-day launch playbook (foundation → first 5 partners → iterate → scale to 15-25), 7 reseller program mistakes that kill momentum (no deal protection, slow payouts, treating all resellers the same, no onboarding, building around largest partner, no conflict resolution, vanity partner counts), and how Covant automates the hard parts (Deal Reg Protection model, automated commissions, conflict detection, audit trails, white-label portal). Cross-links to Covant's Deal Reg Protection attribution model, commission engine, and partner portal features. 21st blog article. Added to sitemap. Ship Log stats updated to 21 blog articles." },
      { hash: "NEW0062", type: "feat", message: "Blog — new SEO article: \"Partner Incentive Programs: How to Design SPIFs, Bonuses & Accelerators That Drive Revenue\" — comprehensive guide targeting 'partner incentive program,' 'SPIF partner program,' and 'partner sales incentives.' Covers why most incentive programs fail (too small to change behavior, everyone qualifies, rules too complex, rewarding results not behavior change, no urgency), the three incentive types that work (SPIFs for short-term behavior change, accelerators for sustained performance, milestone bonuses for strategic objectives), designing effective SPIFs (7-component framework: objective, eligibility, trigger, amount, duration, communication, measurement), building accelerator structures (achievable targets, meaningful rate jumps, marginal-only application, quarterly resets, visible progress), milestone bonuses that build program quality (first deal activation, certification, case studies, engagement, competitive displacement), 7 incentive mistakes that burn budget (stacking until margins disappear, SPIFs too frequent, incentivizing existing revenue, paying on registration, invisible earnings, no post-program analysis, designing in a vacuum), and the complete incentive stack framework (base commission + quarterly accelerators + seasonal SPIFs + milestone catalog + stacking rules). Cross-links to Covant's commission engine features. 20th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 20 blog articles, 125+ shipped items." },
      { hash: "NEW0061", type: "feat", message: "Blog — new SEO article: \"MDF (Market Development Funds): How to Run a Partner Fund That Actually Drives Pipeline\" — comprehensive guide targeting 'market development funds' and 'MDF partner program.' Covers why most MDF programs fail (relationship-based approvals, no pipeline attribution, reimbursement friction, one-size-fits-all design, no performance feedback loop), designing MDF programs that generate pipeline (tiered allocation with earned increases, activity categories with pipeline expectations, milestone-based disbursement, UTM and lead tracking requirements, quarterly performance reviews), the 6-step MDF request-to-disbursement workflow (structured proposals, automatic eligibility checks, manager review with SLA, funds commitment, execution proof, pipeline attribution scoring), three allocation models (revenue percentage, tiered pools, proposal-based competitive), 5 effectiveness metrics (pipeline per MDF dollar, utilization rate, time to pipeline, participation rate, repeat request rate), 7 common MDF mistakes that burn budget (vague awareness funding, MDF as compensation, no clawback, misaligned approvals, static annual budgets, no debriefs, spreadsheet tracking at scale), and building the MDF-to-pipeline connection (CRM-trackable leads, separate MDF-sourced vs partner-sourced pipeline, 90-day attribution windows, partner and activity level ROI). Cross-links to Covant's MDF tracking features. 19th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 19 blog articles, 120+ shipped items." },
      { hash: "NEW0060", type: "feat", message: "Blog — new SEO article: \"Co-Selling with Partners: How to Build a Co-Sell Program That Actually Works\" — comprehensive guide targeting 'co-selling with partners' and 'co-sell program strategy.' Covers why most co-sell programs fail (no defined roles, no shared attribution, misaligned incentives, no operational infrastructure, wrong partner pairings), the three co-sell models that work (sell-with for joint selling, sell-through for influenced deals, sell-to for account mapping and warm intros), building co-sell roles that eliminate confusion (relationship ownership, stage-by-stage leadership, post-sale handoffs, minimum commitments), attribution for multi-partner deals (role categories, credit percentages, touchpoint tracking, audit trails), incentive structures that make co-selling rational (commission uplift, co-sell bonuses, tiered rewards, eliminating the co-sell tax), account mapping as the pipeline engine (customer overlap, prospect overlap, whitespace identification, quarterly refresh cadence), operational infrastructure at scale (shared deal visibility, co-sell deal registration, automated notifications, co-sell reporting, conflict detection), the 90-day launch playbook (select/align → activate/track → close/learn → scale/kill), measuring success (co-sell pipeline, win rate comparison, deal size, time to close, pairing performance, dispute rate), and common mistakes to avoid. Cross-links to Covant's Role Split attribution model and partner portal. 18th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 18 blog articles, 115+ shipped items." },
      { hash: "NEW0059", type: "feat", message: "Blog — new SEO article: \"How to Run a Partner QBR That Actually Drives Action\" — comprehensive guide targeting 'partner QBR' and 'quarterly business review partners.' Covers why most partner QBRs fail (backward-looking data without forward-looking action, no pre-work or structure, wrong people in the room), the 60-minute QBR structure that works (scorecard review, win/loss analysis, pipeline deep dive, action planning, partner feedback), pre-QBR preparation (48-hour scorecard delivery, pre-identified talking points, action item review, agenda sent 72 hours out), the 8-10 metrics that belong in a QBR scorecard (revenue, pipeline, and health categories), tiering your QBR approach by partner segment (strategic 60-min, growth 45-min, tail partners group reviews), making commitments stick after the QBR (24-hour written summaries, monthly check-ins, QBR-to-QBR trend tracking), and common QBR mistakes that kill partner trust. Cross-links to Covant's QBR reports and partner scorecard features. 17th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 17 blog articles, 110+ shipped items." },
      { hash: "NEW0058", type: "feat", message: "Blog — new SEO article: \"Partner Enablement: How to Arm Your Channel to Sell as Well as Your Direct Team\" — comprehensive enablement guide targeting 'partner enablement strategy' and 'how to enable channel partners.' Covers why most enablement fails (content dumps over practical tools, product training instead of sales training, one-time certification instead of continuous reinforcement), the 3-layer enablement framework (First Conversation Kit → Deal Closer Toolkit → Expert Program), content formats that work (2-min videos, battle cards, deal templates, Slack channels), measuring enablement effectiveness (time to first deal reg, win rate, partner confidence score, deal involvement ratio, content utilization), the enablement delivery cadence (weekly micro-updates, monthly live sessions, quarterly refreshes, annual audits), scaling enablement without scaling your team (automated Layer 1, peer enablement, AI-assisted deal coaching, portal as enablement hub), and the enablement-to-revenue connection framework. Cross-links to Covant's partner portal and enablement features. 16th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 16 blog articles." },
      { hash: "NEW0057", type: "feat", message: "Blog — new SEO article: \"How to Design Partner Tiers That Drive Real Growth\" — comprehensive tiering guide targeting 'partner tier structure' and 'how to tier partner program.' Covers why most tier structures fail (input vs output metrics, static annual reviews, wrong number of tiers), the revenue-first tier model (Registered → Authorized → Premier → Strategic with specific revenue thresholds), rolling 12-month evaluation windows vs annual reviews, commission uplift as the real motivator (rate gaps, stacked commission types, transparent publishing, fast payout), secondary tier qualifiers (deal reg quality, customer satisfaction, engagement health, pipeline contribution), communicating upgrades and downgrades, 5 common tier structure mistakes to avoid, 5 metrics for measuring tier system effectiveness, and a practical 30-day tier redesign plan. Cross-links to Covant's tier management, commission rules, and partner portal features. 15th blog article. Added to sitemap and RSS feed. Ship Log stats updated to 15 blog articles, 105+ shipped items." },
    ],
  },
  {
    date: "March 8, 2026",
    commits: [
      { hash: "NEW0056", type: "feat", message: "Blog — new SEO article: \"How to Recruit Channel Partners That Actually Sell\" — comprehensive partner recruitment guide targeting 'how to recruit channel partners' and 'partner recruitment strategy.' Covers why most recruitment fails (no Ideal Partner Profile, selling commissions instead of partnerships, no qualification gate), building an IPP across 5 dimensions (customer overlap, sales motion compatibility, technical capability, capacity, strategic motivation), the 4-stage recruitment pipeline (sourcing → qualification → engagement → activation), outbound vs inbound recruitment strategy, the recruitment pitch framework (their problem → joint value → specifics), recruitment channels ranked by activation rate (shadow partners at 75%+ down to inbound applications at 15-25%), partner count guidance by program stage, and 5 metrics that actually measure recruitment quality (IPP match score, 30-day activation rate, time to first revenue, revenue per partner, cost per activated partner). Cross-links to onboarding article and partner applications page. 14th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0055", type: "feat", message: "Blog — new SEO article: \"How to Evaluate PRM Software: A VP's Buyer Checklist for 2026\" — comprehensive buyer's guide targeting 'PRM software' and 'how to choose PRM' keywords. Five evaluation dimensions: attribution model fit (multi-partner deals, audit trails, model flexibility), commission engine flexibility (tiered rates, product-specific rules, accelerators, split rules), partner portal experience (time-to-first-value, deal reg UX, commission transparency, white-label, mobile), data and intelligence layer (health scoring, revenue intelligence, predictive signals, benchmarking, auto-generated reports), and implementation/time-to-value (setup time, CRM integration, data migration, AI-assisted onboarding, API/webhooks). Includes weighted evaluation scorecard by program maturity, 6 demo questions every VP should ask, and market analysis of legacy vs modern PRM platforms. 13th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0054", type: "feat", message: "Blog — new SEO article: \"Channel Conflict Resolution: The VP's Playbook for Partner Disputes\" — comprehensive guide to managing and resolving channel conflict at scale. Covers the four types of conflict (partner-vs-partner, partner-vs-direct, territory overlap, historical-vs-active), building a conflict resolution framework (preventive rules, detection systems, resolution processes), the deal registration defense (duplicate detection, registration criteria, engagement windows), handling direct-vs-channel competition (registration lock, named accounts, co-sell agreements), the 48-hour resolution protocol, measuring conflict health (conflict rate, resolution time, satisfaction score, repeat rate), and technology requirements for automated conflict management. Targets 'channel conflict resolution' and 'partner conflict management' — high-intent searches from VPs dealing with active dispute problems. Cross-links to Covant's conflict detection engine. 12th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0053", type: "feat", message: "Blog — new SEO article: \"Partner Onboarding: How to Get New Partners to First Deal in 30 Days\" — structured 30-day onboarding framework covering the Day 1/3/7/14/21/30 activation sequence, why most onboarding fails (information overload, no clear next action, no accountability timeline), key metrics (time-to-first-deal, 48h portal login rate, day-30 activation rate, day-90 retention rate), automation for scale (welcome sequences, progress tracking, stalled-partner alerts), the handoff problem between recruiting and onboarding, effective email design, certification layers, and 5 common onboarding mistakes. Targets 'partner onboarding' and 'partner activation best practices' — high-intent searches from VPs building or fixing their onboarding process. 11th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0052", type: "feat", message: "Blog — new SEO article: \"How to Scale Your Partner Program from 10 to 100+ Partners\" — comprehensive scaling playbook covering the three scaling walls (attribution chaos, commission complexity, engagement decay), infrastructure-before-recruitment approach, scalable tier systems, automation priorities, portal as scale multiplier, the 60/20/20 engagement model, stage-appropriate metrics, team structure, and common scaling mistakes. Targets 'how to scale partner program' and 'growing partner program' — high-intent searches from growth-stage VPs hiring their first partner ops person. 10th blog article. Added to sitemap and RSS feed." },
      { hash: "NEW0051a", type: "polish", message: "Ship Log stats updated — 80+ pages, 85+ features, 90+ shipped items." },
      { hash: "NEW0051", type: "feat", message: "Blog — new SEO article: \"The 15 Partner Program KPIs That Actually Matter in 2026\" — comprehensive guide to the metrics VPs of Partnerships should track across attribution & revenue (sourced, influenced, deal size), engagement (active rate, registration velocity, health scores), operations (commission-to-revenue ratio, payout cycle, disputes, win rate), and growth (pipeline coverage, activation rate, concentration risk). Includes benchmarks for each metric and a weekly/monthly/quarterly review cadence. Targets 'partner program KPIs' and 'partner program metrics to track' — high-intent searches from VPs building measurement frameworks. Cross-links to /benchmarks for interactive comparison. 9th blog article. Added to sitemap." },
      { hash: "NEW0050a", type: "polish", message: "Ship Log section on landing page updated — added Mar 8 features (Benchmarks, Templates, Glossary, KPIs blog article), bumped stats to 75+ pages, 80+ features, 85+ shipped items." },
      { hash: "NEW0050", type: "feat", message: "Partner Program Benchmarks (/benchmarks) — interactive industry data page with 16 key metrics across 4 categories (Attribution & Tracking, Commissions & Payouts, Partner Engagement, Revenue & Performance). Each metric shows bottom-quartile, median, and top-quartile ranges with gradient range bars, expert insights, and actionable context. 'Compare Your Program' mode lets VPs enter their own values and see percentile rankings with letter grades, per-metric visual markers on the range bar, and an overall program summary card. Key Takeaways section with 4 strategic insights for 2026. SEO-optimized for 'partner program benchmarks' and 'partner program metrics' — high-intent searches from VPs evaluating or benchmarking their programs. Added to sitemap, footer, and resources hub." },
      { hash: "NEW0049", type: "feat", message: "Partner Program Templates (/templates) — 5 pre-built program blueprints: SaaS Reseller, Referral Network, Technology Alliance, Affiliate, and Co-Sell. Each template includes recommended attribution model, tiered commission structure, partner tiers, key metrics to track, portal features, and when-to-use guidance. Quick selector cards for browsing, per-template launch CTAs linking to demo, and bottom CTA linking to program assessment. Targets 'partner program template' and 'how to structure a reseller program' searches — high-intent queries from VPs building or restructuring programs. Added to footer, sitemap, and resources hub." },
      { hash: "NEW0048", type: "feat", message: "Partner Program Glossary (/glossary) — comprehensive SEO reference page with 33 key terms across 6 categories (Attribution & Tracking, Commissions & Payouts, Partner Management, Deal Flow, Analytics & Reporting, Platform & Operations). Each term includes a clear definition, practical examples, and cross-links to related blog posts, product features, and integration pages. Alphabet jump navigation, category overview cards, and A–Z index for fast lookup. Targets long-tail 'what is partner attribution' and 'what is deal registration' searches that indicate high buyer intent. Added to footer, sitemap, and resources." },
      { hash: "NEW0047", type: "feat", message: "Blog Newsletter Subscribe — email capture component on blog index (card variant) and every blog article (inline variant). Uses existing leads.captureLead mutation with 'blog_newsletter' source tag for tracking. Two variants: card with centered layout for index page, compact inline for end-of-article. Captures high-intent readers who aren't ready to sign up yet but want to follow content. Supports beta outreach — blog readers searching for 'partner attribution' are exactly the audience." },
      { hash: "NEW0046", type: "feat", message: "Blog RSS Feed (/blog/feed.xml) — standard RSS 2.0 feed with Atom self-link for all 8 blog articles. Auto-discovery <link> tag in root layout head. RSS button on blog index page. Improves SEO discoverability (Google crawls RSS feeds for new content) and enables RSS reader subscriptions for beta prospects tracking Covant's content." },
      { hash: "NEW0045", type: "polish", message: "Roadmap page updated — added 5 recently shipped features (Dashboard Preview, Portal Preview, Partner Announcements, Blog RSS, Cookie Consent). Shipped count now 38 and counting." },
      { hash: "NEW0044", type: "polish", message: "Cookie Consent Banner — GDPR/CCPA-compliant cookie consent component on all marketing pages. Accept/decline buttons with preferences persisted via localStorage. Links to privacy policy. Slides up with animation after 1.5s delay. Hidden on dashboard, portal, auth, and admin pages. Enterprise compliance trust signal — VPs evaluating vendors check for privacy compliance." },
    ],
  },
  {
    date: "March 7, 2026",
    commits: [
      { hash: "NEW0043", type: "feat", message: "Site-wide announcement bar — dismissable top banner on all marketing pages promoting early access and beta signup. Gradient background with indigo accent, sparkle icon, inline CTA linking to /beta. Dismiss state persisted via localStorage so it stays hidden once closed. Hidden on dashboard, portal, auth, and admin pages. Drives beta conversion from every marketing page visit." },
      { hash: "NEW0042", type: "feat", message: "Dashboard Preview page (/dashboard-preview) — dedicated marketing page showcasing the admin command center. Six interactive mock UI sections: Program Dashboard (health score, KPIs, action items, trend badges), Attribution Engine (audit trail with calculation chain, touchpoint timeline, model-aware credit), Commission Management (rules by tier/product/deal size, payout summary, dispute tracking), Partner Intelligence (health scores, at-risk detection, partner comparison, scorecards), Reports & Analytics (8 report types with QBR, win/loss, revenue intelligence, weekly digest), and Operations (pipeline kanban, bulk actions, deal registration, team management). Feature grid with 16 admin capabilities. Stats bar (55+ pages, 8 reports, 45+ features, <5 min setup). SEO metadata and Open Graph tags. Added to sitemap, footer, What's New widget. The counterpart to /portal-preview — when VPs evaluate Covant, they want to see both sides: what their partners see AND what they'll see. This page answers the admin side without requiring a demo signup." },
      { hash: "NEW0041", type: "feat", message: "Partner Portal Preview page (/portal-preview) — dedicated marketing page showcasing the partner-facing experience. Six interactive mock UI sections: Portal Dashboard (stats, activity feed), Deal Registration (form with conflict detection, commission rates), Commission Tracking (payout history with attribution), Performance Analytics (tier progress, leaderboard, revenue trends), Certifications (program tracking with progress bars), and Announcements & MDF (program communication feed). Full feature grid with 12 portal capabilities. White-label callout section. Stats bar with key partner experience metrics. SEO metadata and Open Graph tags. Added to sitemap and footer. When VPs evaluate Covant, their #1 question is 'what will my partners see?' — this page answers it without requiring a demo signup." },
      { hash: "NEW0040", type: "feat", message: "Partner Announcements (/dashboard/announcements + /portal/announcements) — broadcast system for partner communication. Admins create announcements with 5 types (General, Product Update, Incentive, Policy Change, Event), draft/publish workflow, pin important items, edit/delete. Stats dashboard with total/published/drafts/pinned counts. Filter by status. Partners see a curated feed in their portal with pinned items at top, type badges, and timestamps. Convex backend with org-scoped CRUD. Added to dashboard sidebar (Program section), portal sidebar, and command palette. Every partner program needs a communication channel — this replaces email blasts with an in-platform feed." },
      { hash: "NEW0039", type: "feat", message: "Features page (/features) — comprehensive reference of all 45+ product capabilities organized into 7 categories: Attribution & Tracking, Commissions & Payouts, Partner Portal, Partner Management, Analytics & Reporting, Platform & Integrations, and Productivity. Each feature card shows icon, description, and deep links to relevant pages. Jump navigation between categories, total feature count, and bottom CTA. The page VPs forward to procurement teams during vendor evaluation — 'does it do X?' answered in one scan. Added to main nav, footer, and sitemap." },
      { hash: "NEW0038", type: "feat", message: "Help Center (/help) — comprehensive knowledge base with 22 guides across 7 categories (Getting Started, Attribution & Tracking, Commissions & Payouts, Partner Portal, Reports & Analytics, Integrations & API, Settings & Admin). Searchable, expandable articles with step-by-step instructions, numbered steps, and related links. Category card navigation. Enterprise trust signal — VPs evaluating vendors check for documentation quality. Added to footer, resources hub, and sitemap." },
      { hash: "NEW0037", type: "feat", message: "Reports Hub (/dashboard/reports) — centralized reports overview page organizing all 8 analytics reports into a navigable card grid. Each card shows report name, description, and color-coded icon with hover effects. Quick-access row for most-used reports (Attribution, Weekly Digest, QBR). Attribution Reports moved to dedicated /dashboard/reports/attribution sub-route. All internal links updated. ⌘K command palette updated with Reports Hub entry. VPs can now discover and navigate to any report from one place instead of hunting through the sidebar." },
      { hash: "NEW0036", type: "polish", message: "Blog article enhancements — article description shown below title, table of contents for articles with 3+ sections, social sharing buttons (LinkedIn, X, copy link), related posts section showing 3 articles at the bottom of each post (same-category first), and Article JSON-LD structured data for Google rich results. Improves SEO indexing, increases time-on-site, and makes blog content more shareable for beta outreach." },
      { hash: "NEW0035", type: "feat", message: "Competitor comparison detail pages — dedicated Covant vs PartnerStack, Covant vs impact.com, and Covant vs Crossbeam (Reveal) pages at /compare/[slug]. Each page: side-by-side feature tables grouped by category with notes, strengths & weaknesses analysis, switch reasons with icons, and honest verdict. Linked from main /compare page with card grid. Added to sitemap. High-intent SEO pages targeting '[competitor] alternative' searches." },
      { hash: "NEW0034", type: "feat", message: "Blog — new SEO article: \"From Gut Feel to Partner Intelligence: How Data Changes Everything\" — deep dive into the five layers of partner intelligence (attribution, health scoring, revenue intelligence, operational intelligence, predictive signals). Targets the 'partner intelligence' keyword that aligns with Covant's core positioning. Practical framework for VPs evaluating their program maturity. Added to sitemap." },
      { hash: "NEW0033", type: "feat", message: "Integration Detail Pages (/integrations/[slug]) — dedicated SEO-optimized landing pages for each integration: Salesforce, HubSpot, Webhooks, REST API, Slack, and Stripe. Each page includes hero stats, key features grid, data flow diagram, step-by-step setup guide, persona-specific use cases, and FAQ section. Cross-links between integration pages. Added to sitemap for search indexing. When a VP asks 'does it work with Salesforce?' — now there's a page to link to." },
      { hash: "NEW0032", type: "feat", message: "Partner Certifications with Convex backend (/dashboard/certifications) — full certification program management replacing the previous 'Coming Soon' placeholder. Create certification programs with level (beginner → expert), category (sales, technical, product, compliance), validity period, and optional tier requirements. Award certifications to partners with optional scores and notes. Track completion status, expiration dates, and revocations. Stats dashboard: active programs, certifications awarded, partner coverage %, expiring-soon alerts. Programs tab with card grid showing award counts, validity, and tier requirements. Awarded tab with sortable table, partner links, level badges, score indicators, and revoke actions. Duplicate prevention, audit trail entries, archive/restore. 6 demo certification programs seeded with 10 partner awards. Convex backend: certifications + partnerCertifications tables with org-scoped indexes, CRUD mutations, stats query. Enterprise partner programs require certifications for tier advancement — this is the missing enablement tracking layer." },
      { hash: "NEW0031", type: "feat", message: "Partner Scorecard (/dashboard/partners/[id]/scorecard) — print-ready, shareable one-page partner performance report. Health score ring chart, 7 key metric cards (revenue, pipeline, win rate, avg deal size, commissions paid/pending), 6-month revenue trend bars, top closed deals table, and auto-generated insights (commission-to-revenue ratio, velocity, trend direction, churn risk). Print/PDF button with optimized print styles. Accessible via Scorecard button on each partner detail page. VPs use this to prep QBRs and share partner performance with leadership." },
      { hash: "NEW0030", type: "feat", message: "Partner Activity Heatmap (/dashboard/reports/activity) — GitHub-style contribution graph showing daily partner program activity over the past 12 months. Aggregates touchpoints, deal registrations, deal closures, and program events into a visual calendar grid. Color intensity scales with activity volume. Hover tooltips show date + event breakdown. Stats row: total events, current streak (consecutive active days), active days count with daily average, and busiest day. Activity breakdown bar chart by event type (touchpoints, deals created, deals closed, program events). Linked from Reports page and command palette. Helps VPs spot engagement patterns, identify quiet periods, and track program momentum at a glance." },
    ],
  },
  {
    date: "March 6, 2026",
    commits: [
      { hash: "NEW0029", type: "feat", message: "Win/Loss Analysis (/dashboard/reports/win-loss) — deep dive into deal outcomes. Overall win rate with deal counts, avg deal size comparison (won vs lost), deal velocity (days to close), revenue totals. Won vs Lost comparison table (touchpoint counts, velocity, size). Monthly 6-month trend with stacked bars. Win rate by deal size bucket, by partner (with tier badges), and by product. Top 5 won deals and recent losses tables. Auto-generated Key Insights: deal size correlation, velocity patterns, touchpoint engagement impact, per-partner outperformance. QBR-ready reporting for VPs." },
      { hash: "NEW0028", type: "feat", message: "Weekly Performance Digest (/dashboard/reports/digest) — automated weekly summary for exec reporting. KPI cards with week-over-week deltas (revenue, deals, partners, touchpoints), win/loss breakdown, pipeline and commissions stats, top partner of the week highlight, notable deals closed, at-risk partner alerts (60+ days inactive), program context footer. Week navigator to browse past weeks. Copy as text for Slack/email, print-friendly layout for exec decks. Linked from Reports page." },
      { hash: "NEW0027", type: "polish", message: "Keyboard shortcuts — press ? to see all available shortcuts. G+key navigation for power users: G then D (Dashboard), G then P (Partners), G then E (Deals), G then S (Settings), and 8 more destinations. Visual indicator shows when G-nav is active. Discoverable via sidebar footer link." },
      { hash: "NEW0026", type: "feat", message: "Advanced deals page — stats cards (won revenue, open pipeline, avg deal size, win rate), 6-filter system (status, partner, product, amount range, registration status), sortable table columns with click-to-sort, active filter pills with individual clear buttons, partner name links in table view, product badges on pipeline cards. Elena's 140-partner workflow: filter to specific partner → sort by amount → find the deal in seconds." },
      { hash: "NEW0025", type: "feat", message: "Revenue Intelligence page (/dashboard/reports/revenue) — deep analytics on partner-attributed revenue. Revenue breakdown by partner type (reseller, referral, affiliate, integration) with donut chart, revenue by tier with horizontal bars, 12-month partner-sourced vs direct revenue trend, revenue concentration risk analysis (top 1/3/5 partner dependency with red flags >60%), top revenue partners leaderboard, and largest closed-won deals table with partner attribution. Commission-to-revenue ratio metric. New Convex query computes all analytics from live deals, partners, and payouts data." },
      { hash: "NEW0024", type: "feat", message: "Partner Comparison — select 2–4 partners from the list and compare side-by-side. Revenue bars, win rate, deal velocity, engagement, commission earned, monthly revenue trends, and auto-generated insights (revenue leader, win rate gaps, engagement alerts, deal size multipliers). Compare button appears in bulk action bar when 2–4 partners are selected. Built for QBR prep — Elena can instantly benchmark her 140 partners against each other." },
      { hash: "NEW0023", type: "feat", message: "Partner Tags — custom labels for organizing partners (e.g. Top Performer, Strategic, At Risk, VIP). Color-coded tag pills on partner detail page and partners list table. Add/remove tags inline with suggested tag dropdown. Filter partners by tag on the list page. 8 pre-defined color-coded tags plus support for custom tags. Convex schema + updateTags mutation + listAllTags query. Seed data includes tags on all 5 demo partners. Every VP of Partnerships organizes their channel by labels — this is table stakes CRM functionality." },
      { hash: "NEW0022", type: "feat", message: "Partner Notes — threaded internal notes system on partner detail page. Team members can add timestamped notes about conversations, follow-ups, and escalations. Pin important notes to top, inline edit, delete. Convex backend with org-scoped queries and audit trail. Core relationship management feature for partner managers tracking context across team members." },
      { hash: "3940b95", type: "feat", message: "Portal volume page wired to real Convex data — volume programs, partner volume records, tier progress, and leaderboard rankings now persist in Convex instead of local useStore. All portal pages now use real Convex data with zero useStore dependencies remaining." },
      { hash: "76cb6e7", type: "feat", message: "Portal territory page wired to real Convex data — partner territories, assigned accounts, and channel conflicts now persist in Convex instead of local useStore. New territories and channelConflicts tables in schema, portalTerritories.ts query with partner-scoped data, conflict alerts with other partner names, deal status badges on accounts. Loading skeleton, empty state. Seeded demo territories and conflicts for all 5 Horizon partners." },
      { hash: "16c5be6", type: "feat", message: "Portal products page wired to real Convex data — replaces useStore demo data with live org products, partner-specific commission rates from commission rules, and per-product deal activity from real touchpoints and deal registrations." },
      { hash: "NEW0021", type: "feat", message: "Tier reviews wired to Convex — approve, reject, or defer partner tier changes with full persistence. Previously all review decisions were lost on page refresh (local state only). Now saves to Convex tierReviews table with audit trail entries. Bulk approve remaining, debounced notes auto-save, loading skeletons. Scoring data pulled from real Convex partners/deals/touchpoints/attributions instead of demo store." },
      { hash: "15d4a61", type: "feat", message: "What's New changelog widget in dashboard top bar — sparkle button opens a curated dropdown panel showing recent feature highlights with type badges (New/Fix/Polish), descriptions, and click-to-navigate links to relevant dashboard pages. Green dot badge when unseen features exist. Read state tracked via localStorage. Links to full /changelog page." },
    ],
  },
  {
    date: "March 5, 2026",
    commits: [
      { hash: "39af0c2", type: "feat", message: "Goals & Targets page at /dashboard/goals — set quarterly objectives for revenue, pipeline, partners, deals, and win rate. Track live progress from real Convex data with color-coded pace indicators, stats summary, inline editing, and period/status filters. Added to Analytics sidebar nav." },
      { hash: "NEW0019", type: "feat", message: "System Status page at /status — public-facing service health dashboard showing 8 monitored services (Web App, API, Attribution Engine, Commission Engine, Auth, Database, Portal, Integrations), 90-day uptime bar, incident history timeline, and contact CTA. Enterprise trust signal for beta prospects. Added to footer, sitemap." },
      { hash: "96fdc8a", type: "feat", message: "Engine-based pricing — rebuilt /pricing with modular AI engine model. Four engines (Attribution, Incentives, Intelligence, CRM) selectable individually or as a discounted bundle. Three partner tiers (Starter ≤25, Growth ≤100, Scale unlimited). Partner Portal always free. Free tier up to 5 partners with no engines required. Updated FAQ and stale pricing references across landing page, resources, and legal pages." },
      { hash: "NEW0018", type: "polish", message: "Rich activity feed on dashboard — replaced raw audit log entries with a polished timeline component. Action-specific icons and color coding for 20+ event types (deals, commissions, disputes, team changes, touchpoints, tier changes). Human-readable descriptions parsed from metadata. Relative timestamps (\"2h ago\"). Clickable entries link to relevant pages. Empty state with guidance." },
      { hash: "6198bff", type: "polish", message: "ROI calculator redesign — 3 intuitive sliders (partners, avg deal size, deals/month) with conservative assumptions and clean real-time output. Replaces complex form inputs with drag-to-calculate UX. Shows annual time saved, dispute reduction, and net ROI." },
      { hash: "3a4dc2f", type: "other", message: "Removed founding member pricing section from landing page — cleaner hero focus, reduces friction for beta signups." },
      { hash: "e5cd02c", type: "feat", message: "Data Export Center — centralized bulk CSV download page at /dashboard/reports/export. Download all program data (partners, deals, payouts, touchpoints, audit log, commission rules, products) as CSV files. Record counts per data type, download buttons, completion indicators. New Convex export queries with org-scoped data access. Linked from Attribution Reports page. Enterprise-grade data portability for beta users." },
      { hash: "c4495ff", type: "feat", message: "Portal dashboard wired to real Convex data — partner home page now pulls stats (total earned, pending, deals won, revenue influenced), recent touchpoints, and deal list from live Convex queries instead of hardcoded demo data. New `convex/portalDashboard.ts` with `getStats`, `getDeals`, `getRecentTouchpoints`, `getPayouts` queries (all partner-scoped). Loading skeleton, empty states with CTAs, enriched touchpoint feed showing deal names and amounts. Removed useStore dependency from portal home page. Partners now see their real data the moment they log in." },
      { hash: "6012dec", type: "feat", message: "Partner Leaderboard — gamified performance rankings at /dashboard/leaderboard. Top-3 podium with medals, time period filters (30d/90d/all-time), multi-sort (composite score, revenue, deals, win rate, engagement), tier badges, composite score bars, commission summary. Convex-powered rankings with weighted scoring (revenue 35%, deals 25%, win rate 20%, engagement 20%). Added to Analytics sidebar nav. Drives partner competition and gives VPs instant visibility into who's performing." },
      { hash: "3ce37d9", type: "feat", message: "Portal MDF page wired to real Convex data — partner-submitted MDF requests now persist across sessions. New partner-scoped queries (getByPartner, submitRequest, getPartnerStats), loading skeleton, empty state, review notes. Completes the MDF workflow end-to-end: partners submit → admins review → status flows back to portal." },
      { hash: "9e3218f", type: "polish", message: "Performance consolidation — merged duplicate dashboard queries, dynamic imports for Recharts and command palette, RSC layout split for faster initial loads." },
      { hash: "9e18445", type: "feat", message: "Partner Health page wired to real Convex data — individual health scores (0-100) computed from live deal activity, revenue, touchpoint engagement, recency, and payout health. Auto-classifies partners as healthy/at-risk/churning/new with contextual signals and recommended actions." },
      { hash: "aa36433", type: "feat", message: "Program Health Score on main dashboard — composite 0-100 score across four categories: Partner Engagement (touchpoint activity in 90 days), Deal Velocity (win rate + recent deals), Payout Health (paid vs pending ratio), and Program Growth (new partners + deals in 30 days). Color-coded progress bar with category breakdown cards. One number for VPs to report on program health." },
      { hash: "bffd14f", type: "feat", message: "Performance analytics on partner detail page — revenue by month bar chart (last 6 months), deal stage breakdown with color-coded counts, touchpoint type distribution donut chart. Responsive grid layout, only renders when data exists. Answers \"is this partner trending up or down?\" at a glance." },
      { hash: "a8a9ddd", type: "feat", message: "Add Touchpoint wired to Convex — deal detail \"+ Touchpoint\" button now creates real touchpoints with Clerk auth. All 9 touchpoint types available (referral, demo, content share, introduction, proposal, negotiation, deal registration, co-sell, technical enablement). Remove button on each touchpoint for open deals. Audit log entries for create/delete. Completes the attribution data entry workflow." },
      { hash: "eab51c4", type: "feat", message: "Quarterly Business Review (QBR) report page — executive summary with Q-over-Q delta badges for revenue, pipeline, partners, and win rate. 12-month rolling revenue & pipeline area chart, pipeline breakdown pie chart, commission summary with C-to-R ratio, top 5 partner leaderboard with medals, action items grid, quarter progress bar. Print/PDF support. Linked from Attribution Reports." },
      { hash: "NEW0016", type: "polish", message: "Period-over-period trend badges on all 4 dashboard stat cards — each card now shows \"↑ X% vs last month\" or \"↓ X% vs last month\" computed from real Convex trend data. Green for growth, red for decline, neutral for flat. Answers the #1 VP question: \"are we trending up or down?\"" },
      { hash: "2ec1248", type: "polish", message: "Loading skeletons for all 27 dashboard pages — reusable DashboardSkeleton component with 5 layout variants (TablePage, CardPage, ChartPage, SettingsPage, SimplePage). Shimmer animations matched to each page layout. Replaces blank/flash states while Convex queries resolve." },
      { hash: "NEW0014", type: "feat", message: "Dispute resolution with Convex backend — full dispute lifecycle: open disputes against deals with current/requested commission %, review workflow, resolve or reject with notes, CSV export, audit trail. Convex backend: disputes table with list, getCounts, create, updateStatus, remove mutations, org-scoped queries. Duplicate dispute prevention. Added to sidebar nav under Revenue. Replaces local-state-only conflicts page." },
    ],
  },
  {
    date: "March 4, 2026",
    commits: [
      { hash: "e36f14e", type: "polish", message: "Breadcrumb navigation — auto-generated breadcrumbs for all 45+ dashboard pages. Human-readable labels for every segment, Home icon anchor, dynamic Convex ID detection, styled in dark aesthetic. Appears on every dashboard sub-page for better wayfinding." },
      { hash: "NEW0012", type: "feat", message: "Pipeline kanban board — new Board view toggle on /dashboard/pipeline showing deals in 4 columns (Pending Registration → Active Pipeline → Closed Won → Closed Lost). Each column shows deal count and total value. Compact deal cards with product badges, registration status, and partner info. Grid view preserved as alternative." },
      { hash: "feecedd", type: "feat", message: "Product-aware commission rules — commission rules settings now pulls from product catalog with grouped dropdown by category. Portal deal registration includes product selector. Dashboard deals table shows product badge column. Attribution calculator matches productLine rules against deal.productName (was a TODO). Seed data updated with 6 product-tagged demo deals." },
      { hash: "991d277", type: "feat", message: "Product catalog with Convex backend — full CRUD at /dashboard/products with SKU and name search, category filter, active/inactive toggle, inline edit modal with live margin preview, delete confirmation. Stats row (total products, active/inactive, avg margin, catalog value). Schema: products table with org-scoped indexes. 8 demo products seeded. Added to sidebar nav under Revenue." },
      { hash: "NEW0010", type: "feat", message: "API Keys management — create named API keys with granular scopes (partners, deals, payouts, commissions, attributions, webhooks), expiration options (30d/90d/1y/never), key shown once on creation with copy button, revoke with confirmation, active/revoked views, 10-key limit per org. Full Convex backend with org-scoped CRUD. Linked from settings quick links." },
      { hash: "e58d8f9", type: "feat", message: "Notifications center — full inbox at /dashboard/notifications with type-based filtering (deals, partners, revenue, disputes, system), unread filter with badge count, bulk select + mark-read, date-grouped timeline, per-notification actions, stats row. Bell dropdown now links here instead of activity log. Added to sidebar nav." },
      { hash: "672468a", type: "feat", message: "Notification preferences — per-event in-app and email notification toggles at /dashboard/settings/notifications. Configure which events trigger notifications (deals, revenue, partners, system), set email digest frequency (off/instant/daily/weekly), and quiet hours for non-critical alerts. Linked from settings quick links." },
      { hash: "e4c9a40", type: "feat", message: "Partner applications — public /apply form (company info, partnership type selector, team size, message) + admin review dashboard at /dashboard/partner-applications with approve/reject workflow, review notes, status filters, counts. Duplicate email detection. Added to sidebar, footer, and sitemap." },
      { hash: "b48bec7", type: "feat", message: "Outbound webhooks — create endpoints with URL and event subscriptions, HMAC signing secrets (auto-generated, reveal/copy/rotate), pause/activate toggle, send test events, delivery log with status codes, edit/delete endpoints. 15 event types across Deals, Partners, Payouts, Commissions, and Attribution. Full Convex backend with CRUD, secret rotation, and test delivery logging. Sample payload docs. Linked from settings." },
      { hash: "NEW0007", type: "feat", message: "Team management — invite teammates, assign roles (Admin/Manager/Member), change roles inline, remove members with confirmation. Full Convex backend with org scoping, admin-only guards, last-admin protection, and audit logging. Linked from settings quick links and settings page." },
      { hash: "620fa50", type: "feat", message: "Interactive demo walkthrough — 5-step guided product tour (Dashboard, Attribution, Commissions, Portal, Launch) with mock UI panels. Pre-seeds data in background. Skip option, progress bar, responsive." },
      { hash: "NEW0006", type: "feat", message: "Customer stories page — 3 illustrative case studies (Meridian Cloud, StackPath Analytics, Nova Security) showing before/after results for partner program transformations. Covers Deal Reg Protection, Source Wins, and Role Split attribution models. Added to nav, footer, sitemap, and resources hub." },
      { hash: "NEW0005", type: "feat", message: "Use case detail pages — dedicated landing pages for VP Partnerships, RevOps, and Partner Manager personas at /use-cases/[slug]. Each page: hero stats, problem narrative, solution walkthrough, before/after comparison, VP quote, outcomes, and cross-links. Optimized for outreach URLs in cold emails and LinkedIn DMs." },
      { hash: "NEW0004", type: "feat", message: "Blog — 2 new SEO articles: \"How to Build a Partner Portal That Partners Actually Use\" (login friction, 2-minute visit design, deal reg UX, commission transparency, engagement metrics) and \"Partner Program ROI: How to Prove Your Channel Is Worth the Investment\" (CAC comparison, cycle acceleration, deal size lift, RPP, CFO-ready ROI model). 7 total blog posts now." },
      { hash: "NEW0003", type: "feat", message: "Blog — 2 new SEO articles: \"How to Build a Partner Commission Structure That Scales\" (tiered commission design, role-based rates, performance layers) and \"Partner Deal Registration: The Complete Guide for 2026\" (5-step workflow, SLA best practices, metrics)." },
    ],
  },
  {
    date: "March 3, 2026",
    commits: [
      { hash: "NEW0002", type: "feat", message: "Blog — 3 SEO-optimized articles for beta outreach: partner attribution breakdown, spreadsheet cost analysis, and attribution models guide. Index page, individual article pages, footer + sitemap integration" },
      { hash: "433d511", type: "polish", message: "SEO metadata + JSON-LD structured data across all marketing pages — page-specific titles/descriptions, Organization/WebSite/SoftwareApplication schemas, FAQPage schema for rich results" },
      { hash: "NEW0001", type: "feat", message: "FAQ page — 24 questions across 6 categories (getting started, attribution, integrations, portal, security, pricing) for beta outreach and SEO" },
      { hash: "70f14a4", type: "feat", message: "Founding member offer — live beta counter, social proof with role/company attribution, urgency-driven early access CTA" },
      { hash: "252b386", type: "feat", message: "Public product roadmap — shipped/in-progress/planned features with stats, quarter targets, and beta CTA. Added to footer, sitemap, and resources" },
      { hash: "85ba61e", type: "feat", message: "Product tour page — visual walkthrough of every platform module with interactive mockups, jump navigation, and CTAs. Added to main nav, footer, and sitemap" },
      { hash: "a74c4be", type: "polish", message: "Shared Footer component — extracted into reusable component, now renders across all marketing pages with responsive 4→2→1 column grid" },
      { hash: "539fd31", type: "feat", message: "Resources hub — centralized library with guides, templates, tools, and partner success content for beta outreach" },
      { hash: "5651132", type: "feat", message: "Contact page — lead capture form with partner count selector, quick contact sidebar, \"What to expect\" guide. Enterprise + ROI CTAs now route to /contact" },
      { hash: "f6dd2c3", type: "feat", message: "Partner program assessment — interactive 8-question maturity quiz with scoring, personalized recommendations, and lead capture for outreach" },
      { hash: "42e0b13", type: "fix", message: "ROI calculator pricing fix — was showing old ARR-based tiers, now uses real partner-count pricing (Free/Pro/Scale/Enterprise). New standalone /roi page for outreach linking" },
      { hash: "8d6ec87", type: "feat", message: "Email notifications wired to real Convex data — templates CRUD, toggle enable/disable, inline editing, auto-seed defaults, live queue stats, org-scoped queries" },
      { hash: "c36e44e", type: "feat", message: "Command palette live search — ⌘K now searches real partners and deals from Convex, not just static page navigation" },
      { hash: "6fb18df", type: "feat", message: "Compare page — competitive positioning table (Covant vs. Spreadsheets vs. Legacy PRM vs. Ecosystem Tools) for beta outreach" },
      { hash: "f860ede", type: "feat", message: "Real sparkline trends — dashboard stat cards pull 12-month rolling data from Convex instead of hardcoded arrays, new getTrends query" },
      { hash: "4475e85", type: "feat", message: "Dashboard action items wired to real Convex data — tier reviews, onboarding partners, unpaid commissions, pending deal regs, email triggers, pending invites" },
      { hash: "7f9c2e1", type: "feat", message: "Integrations page — CRM, webhooks, API, Stripe showcase with feature details for beta outreach" },
      { hash: "d903acb", type: "feat", message: "Getting started checklist — guided onboarding steps on dashboard for new users, auto-detects completion" },
      { hash: "ce91cb5", type: "polish", message: "Onboard loading state — spinner while Clerk + Convex provision the org" },
      { hash: "20c3093", type: "feat", message: "About page — company story, values, and problem statement for beta outreach" },
      { hash: "ac2ee91", type: "feat", message: "Error boundaries + loading states — global error page, setup/onboard error recovery" },
    ],
  },
  {
    date: "March 2, 2026",
    commits: [
      { hash: "1674657", type: "polish", message: "Vercel Analytics added to layout, beta page responsive grid for mobile" },
      { hash: "5cb6f32", type: "feat", message: "SEO + GTM — sitemap.xml, robots.txt, og:image, /beta waitlist page with lead capture, 'Join Beta' CTA on hero" },
      { hash: "04c2a3a", type: "feat", message: "Real signup flow + org isolation — /onboard provisions Convex org on first Clerk login, dashboard protected by middleware, pricing CTAs → /sign-up" },
    ],
  },
  {
    date: "March 1, 2026",
    commits: [
      { hash: "6373b9e", type: "feat", message: "Pricing page rebuild — Free/Pro/Scale/Enterprise tiers, partner-count metric, no time-limited trial" },
      { hash: "a20080d", type: "feat", message: "Compliance docs — /privacy, /terms, /security, /dpa all live with full legal content" },
      { hash: "2f79d3a", type: "feat", message: "Real data onboarding as primary entry point — hero CTA → /setup, demo banner in dashboard" },
    ],
  },
  {
    date: "February 28, 2026",
    commits: [
      { hash: "8a82b10", type: "fix", message: "UX polish — filter zero-win recommended partners, fix deals double-listing, billing spinner, portal branding, sidebar clip" },
      { hash: "07c64b2", type: "fix", message: "Pricing CTA text consistency, remove duplicate View Demo nav link" },
      { hash: "37ae7e5", type: "fix", message: "Lazy Stripe init — avoid build-time crash when STRIPE_SECRET_KEY not set" },
      { hash: "0e3a45c", type: "feat", message: "Stripe billing — checkout sessions, webhooks, customer portal, pricing CTAs, billing settings page" },
    ],
  },
  {
    date: "February 26, 2026",
    commits: [
      { hash: "113e784", type: "feat", message: "Clerk auth — sign-in/sign-up pages with Covant dark branding, demo banner, portal UserButton" },
    ],
  },
  {
    date: "February 23, 2026",
    commits: [
      { hash: "ed8f449", type: "feat", message: "Enriched seed data — 22 deals (was 7), 26 audit log entries, varied partner profiles across all 5 partners" },
      { hash: "b2a6cf0", type: "feat", message: "Portal referrals + dashboard cohorts wired to real Convex data" },
      { hash: "49e5c67", type: "fix", message: "Auto-create commission on deal registration approval" },
      { hash: "0debef1", type: "feat", message: "Portal performance page — personal stats, tier/score breakdown, commission trend, deals table" },
      { hash: "d891fa7", type: "feat", message: "Benchmarks page — partner performance vs program averages, tier distribution, top/bottom quartile" },
      { hash: "f773a0c", type: "feat", message: "Forecasting page — pipeline & commission projections from real deal data, scenario toggle" },
      { hash: "57a9502", type: "feat", message: "Contracts page — real Convex data, status changes, expandable details, CSV export" },
      { hash: "e5e353f", type: "polish", message: "Empty state improvements for deals, partners, and portal commissions pages" },
      { hash: "77e4456", type: "fix", message: "Orphaned pages audit — added navigation links to 6 previously unreachable pages" },
    ],
  },
  {
    date: "February 22, 2026",
    commits: [
      { hash: "1d116e7", type: "feat", message: "Portal notifications wired to real Convex data with unread badges" },
      { hash: "5689498", type: "feat", message: "Partner detail page — onboarding progress bar + audit trail" },
      { hash: "e091edf", type: "feat", message: "Bulk payout approval — checkbox select + batch approve on payouts page" },
      { hash: "6460b46", type: "feat", message: "Partner onboarding completion tracking with progress bar on partners table" },
      { hash: "b8b2ed3", type: "feat", message: "End-of-quarter reconciliation report with quarter filter and CSV export" },
      { hash: "d2fff0c", type: "feat", message: "Deal registration workflow — partners register deals, admins approve/reject" },
      { hash: "41187a6", type: "feat", message: "Complex commission rules — Phase 3: settings UI at /dashboard/settings/commission-rules" },
      { hash: "1c0a86c", type: "feat", message: "Complex commission rules — Phase 2: wired into attribution calculator" },
      { hash: "1a9f52f", type: "feat", message: "Complex commission rules — Phase 1: schema, CRUD, rule matching, seed data" },
      { hash: "0246086", type: "fix", message: "Link audit — ensure all expected navigation clicks work across the app" },
      { hash: "e1687b3", type: "fix", message: "Invite page render-loop bug — moved pre-fill logic into useEffect" },
      { hash: "2e503f5", type: "feat", message: "Partner invite flow — invite link → profile form → portal access in under 10 minutes" },
      { hash: "8df55e5", type: "fix", message: "Added confirmation dialog when changing attribution model in config" },
    ],
  },
  {
    date: "February 21, 2026",
    commits: [
      { hash: "2c9dcdf", type: "feat", message: "Config editability — edit program config post-setup from settings page" },
      { hash: "401cc43", type: "feat", message: "Portal white-label — removed all Covant branding from partner-facing pages" },
    ],
  },
  {
    date: "February 20, 2026",
    commits: [
      { hash: "9f2c7f3", type: "fix", message: "Audit trail math formula — show actual calculation chain instead of misleading touchpoint × rate" },
      { hash: "06afd43", type: "feat", message: "Deal Reg Protection, Source Wins, Role Split — three real-world attribution models" },
      { hash: "e11434c", type: "feat", message: "Attribution audit trail on deal detail — per-partner paper trail for every payout" },
      { hash: "80c1d03", type: "feat", message: "Setup → real config — Convex persistence, live preview panel, dashboard welcome banner" },
      { hash: "86a4f96", type: "fix", message: "Setup AI — correct model, strip leading assistant message, plain text streaming" },
      { hash: "4beee49", type: "fix", message: "Setup page broken model name, wired /setup into nav + pricing CTAs" },
    ],
  },
];

const TYPE_CONFIG = {
  feat: { label: "Feature", color: "#22c55e", bg: "#22c55e18", icon: Sparkles },
  fix: { label: "Fix", color: "#f59e0b", bg: "#f59e0b18", icon: Wrench },
  polish: { label: "Polish", color: "#8b5cf6", bg: "#8b5cf618", icon: Zap },
  other: { label: "Update", color: "#6b7280", bg: "#6b728018", icon: GitCommit },
};

export default function ChangelogPage() {
  const totalFeatures = CHANGELOG.flatMap((e) => e.commits).filter((c) => c.type === "feat").length;
  const totalFixes = CHANGELOG.flatMap((e) => e.commits).filter((c) => c.type === "fix" || c.type === "polish").length;

  return (
    <div style={{ maxWidth: 720, margin: "0 auto", padding: "3rem 1.5rem" }}>
      {/* Header */}
      <div style={{ marginBottom: "2.5rem" }}>
        <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 6, color: "var(--muted)", fontSize: ".85rem", textDecoration: "none", marginBottom: 12 }}>
          <ArrowLeft size={14} /> Back to Covant
        </Link>
        <h1 style={{ fontSize: "2rem", fontWeight: 800, letterSpacing: "-0.02em" }}>Changelog</h1>
        <p className="muted" style={{ marginTop: ".25rem", lineHeight: 1.6 }}>
          What&apos;s new in Covant — {totalFeatures} features and {totalFixes} improvements shipped so far.
        </p>
      </div>

      {/* Timeline */}
      <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
        {CHANGELOG.map((entry) => (
          <div key={entry.date}>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}>
              <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#6366f1", flexShrink: 0 }} />
              <h2 style={{ fontSize: "1rem", fontWeight: 700, margin: 0 }}>{entry.date}</h2>
              <span className="muted" style={{ fontSize: ".75rem" }}>({entry.commits.length} changes)</span>
            </div>
            <div style={{ marginLeft: 5, borderLeft: "2px solid var(--border)", paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
              {entry.commits.map((c) => {
                const cfg = TYPE_CONFIG[c.type];
                const Icon = cfg.icon;
                return (
                  <div key={c.hash} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
                    <span style={{
                      display: "inline-flex", alignItems: "center", gap: 4, padding: "2px 8px",
                      borderRadius: 6, fontSize: ".65rem", fontWeight: 700, color: cfg.color, background: cfg.bg,
                      flexShrink: 0, marginTop: 2,
                    }}>
                      <Icon size={10} /> {cfg.label}
                    </span>
                    <span style={{ fontSize: ".85rem", lineHeight: 1.5 }}>
                      {c.message}
                      <code style={{ fontSize: ".7rem", color: "var(--muted)", marginLeft: 6 }}>{c.hash}</code>
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
