import type { IncentiveProgram, IncentiveEnrollment } from "./types";

const now = Date.now();
const DAY = 86400000;

export const demoIncentivePrograms: IncentiveProgram[] = [
  {
    _id: "prog_q1_spif",
    name: "Q1 Cloud Migration SPIF",
    type: "spif",
    description: "Extra $500 per closed cloud migration deal through March 2026",
    status: "active",
    startDate: now - 45 * DAY,
    endDate: now + 45 * DAY,
    budget: 50000,
    spent: 18500,
    rules: [
      { metric: "deals_closed", threshold: 1, reward: 500, rewardType: "flat", description: "$500 per closed cloud migration deal" },
      { metric: "deals_closed", threshold: 5, reward: 1000, rewardType: "flat", description: "Bonus $1,000 for 5+ deals (accelerator)" },
    ],
    eligiblePartnerTiers: ["silver", "gold", "platinum"],
    eligiblePartnerTypes: ["reseller", "referral"],
    createdAt: now - 50 * DAY,
  },
  {
    _id: "prog_new_logo",
    name: "New Logo Bonus Program",
    type: "bonus",
    description: "3% bonus on first deal with any net-new customer",
    status: "active",
    startDate: now - 90 * DAY,
    endDate: now + 90 * DAY,
    budget: 100000,
    spent: 34200,
    rules: [
      { metric: "new_logos", threshold: 1, reward: 3, rewardType: "percentage", description: "3% bonus on new logo revenue" },
      { metric: "new_logos", threshold: 10, reward: 5, rewardType: "percentage", description: "5% for 10+ new logos (tier upgrade)" },
    ],
    eligiblePartnerTiers: ["bronze", "silver", "gold", "platinum"],
    eligiblePartnerTypes: ["reseller", "referral", "affiliate"],
    createdAt: now - 95 * DAY,
  },
  {
    _id: "prog_cert_accel",
    name: "Certification Accelerator",
    type: "accelerator",
    description: "Partners earn rebate multipliers by completing certifications",
    status: "active",
    startDate: now - 60 * DAY,
    endDate: now + 120 * DAY,
    budget: 25000,
    spent: 8750,
    rules: [
      { metric: "certifications", threshold: 2, reward: 1.25, rewardType: "percentage", description: "1.25x rebate multiplier at 2 certs" },
      { metric: "certifications", threshold: 5, reward: 1.5, rewardType: "percentage", description: "1.5x rebate multiplier at 5 certs" },
    ],
    eligiblePartnerTiers: ["gold", "platinum"],
    eligiblePartnerTypes: ["reseller", "integration"],
    createdAt: now - 65 * DAY,
  },
  {
    _id: "prog_deal_reg",
    name: "Deal Registration Fast-Track",
    type: "deal_reg_bonus",
    description: "Extra 2% commission on all registered deals approved within 48h",
    status: "active",
    startDate: now - 30 * DAY,
    endDate: now + 150 * DAY,
    budget: 75000,
    spent: 12300,
    rules: [
      { metric: "deal_registrations", threshold: 1, reward: 2, rewardType: "percentage", description: "+2% on registered deals" },
    ],
    eligiblePartnerTiers: ["silver", "gold", "platinum"],
    eligiblePartnerTypes: ["reseller"],
    createdAt: now - 35 * DAY,
  },
  {
    _id: "prog_fy25_mdf",
    name: "FY25 MDF Match",
    type: "mdf_match",
    description: "1:1 MDF match for qualified marketing activities",
    status: "ended",
    startDate: now - 200 * DAY,
    endDate: now - 20 * DAY,
    budget: 200000,
    spent: 187400,
    rules: [
      { metric: "revenue", threshold: 50000, reward: 10000, rewardType: "flat", description: "$10K MDF match at $50K revenue" },
      { metric: "revenue", threshold: 200000, reward: 50000, rewardType: "flat", description: "$50K MDF match at $200K revenue" },
    ],
    eligiblePartnerTiers: ["gold", "platinum"],
    eligiblePartnerTypes: ["reseller", "integration"],
    createdAt: now - 210 * DAY,
  },
];

export const demoIncentiveEnrollments: IncentiveEnrollment[] = [
  {
    _id: "enr_1",
    programId: "prog_q1_spif",
    partnerId: "p1",
    partnerName: "Stackline",
    enrolledAt: now - 40 * DAY,
    progress: [{ metric: "deals_closed", current: 7, target: 5 }],
    earned: 4500,
    paid: 3500,
    status: "achieved",
  },
  {
    _id: "enr_2",
    programId: "prog_q1_spif",
    partnerId: "p2",
    partnerName: "Clearpath",
    enrolledAt: now - 38 * DAY,
    progress: [{ metric: "deals_closed", current: 3, target: 5 }],
    earned: 1500,
    paid: 1500,
    status: "enrolled",
  },
  {
    _id: "enr_3",
    programId: "prog_q1_spif",
    partnerId: "p3",
    partnerName: "Apex Growth",
    enrolledAt: now - 35 * DAY,
    progress: [{ metric: "deals_closed", current: 12, target: 5 }],
    earned: 7000,
    paid: 6000,
    status: "achieved",
  },
  {
    _id: "enr_4",
    programId: "prog_new_logo",
    partnerId: "p1",
    partnerName: "Stackline",
    enrolledAt: now - 85 * DAY,
    progress: [{ metric: "new_logos", current: 8, target: 10 }],
    earned: 12600,
    paid: 9000,
    status: "enrolled",
  },
  {
    _id: "enr_5",
    programId: "prog_new_logo",
    partnerId: "p4",
    partnerName: "Northlight",
    enrolledAt: now - 80 * DAY,
    progress: [{ metric: "new_logos", current: 14, target: 10 }],
    earned: 21600,
    paid: 18000,
    status: "achieved",
  },
  {
    _id: "enr_6",
    programId: "prog_cert_accel",
    partnerId: "p2",
    partnerName: "Clearpath",
    enrolledAt: now - 55 * DAY,
    progress: [{ metric: "certifications", current: 4, target: 5 }],
    earned: 3750,
    paid: 2500,
    status: "enrolled",
  },
  {
    _id: "enr_7",
    programId: "prog_deal_reg",
    partnerId: "p3",
    partnerName: "Apex Growth",
    enrolledAt: now - 25 * DAY,
    progress: [{ metric: "deal_registrations", current: 6, target: 1 }],
    earned: 8400,
    paid: 4200,
    status: "achieved",
  },
  {
    _id: "enr_8",
    programId: "prog_deal_reg",
    partnerId: "p1",
    partnerName: "Stackline",
    enrolledAt: now - 20 * DAY,
    progress: [{ metric: "deal_registrations", current: 3, target: 1 }],
    earned: 3900,
    paid: 0,
    status: "achieved",
  },
];
